//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoaQuickTrips
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedCustomer
    {
        public int BCID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
