//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoaQuickTrips
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.ReviewDetails = new HashSet<ReviewDetail>();
        }
    
        public int ReviewID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> ApartmentID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string Review1 { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewDetail> ReviewDetails { get; set; }
    }
}
