//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoaQuickTrips
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewDetail
    {
        public int ReviewDetailID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string Reply { get; set; }
        public Nullable<bool> ISvisible { get; set; }
    
        public virtual Review Review { get; set; }
    }
}
